CREATE DATABASE CRAWL;
USE CRAWL;

CREATE TABLE ARTICLES (
	board VARCHAR(30) NOT NULL,
	articleId VARCHAR(14) NOT NULL,
	title TEXT NOT NULL,
	author TEXT NOT NULL,
	department TEXT NOT NULL,
	postTime VARCHAR(20) NOT NULL,
	hits INT NOT NULL,
	contents MEDIUMTEXT NOT NULL,
	PRIMARY KEY (articleId)
);

CREATE TABLE ATTACHEDLINKS (
	id INT NOT NULL AUTO_INCREMENT,
	articleId VARCHAR(14) NOT NULL,
	linkPath TEXT,
	PRIMARY KEY (id)
);

CREATE TABLE IMAGELINKS (
	id INT NOT NULL AUTO_INCREMENT,
	articleId VARCHAR(14) NOT NULL,
	imagePath TEXT,
	PRIMARY KEY (id)
);

ALTER TABLE ARTICLES CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE ATTACHEDLINKS CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE IMAGELINKS CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
