CREATE DATABASE CRAWL;
USE CRAWL;

CREATE TABLE ARTICLES (
	borad VARCHAR(30) NOT NULL,
	articleId INTEGER NOT NULL PRIMARY KEY,
	title VARCHAR(50) NOT NULL,
	author VARCHAR(20) NOT NULL,
	department VARCHAR(30) NOT NULL,
	postTime DATETIME NOT NULL,
	hits INT NOT NULL,
	attached INTEGER,
	contents MEDIUMTEXT NOT NULL,
	images INTEGER
);

CREATE TABLE ATTACHEDLINKS (
	attachKey INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
	attachId INTEGER,
	linkPath VARCHAR(30)
);

CREATE TABLE IMAGELINKS (
	imageKey INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
	imageId INTEGER,
	imagePath VARCHAR(30)
);

ALTER TABLE ARTICLES CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
